spring:
  profiles:
    active: local # default
    group:
      local:
        - common
      prod: # operating server profile
        - common

---

spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: 15224a9e4cb6260a357323ba3cf4dd6c
# ...

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    #driver-class-name: org.mariadb.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/pharmacy-recommendation
    url: jdbc:mysql://localhost:3306/project2
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

pharmacy:
  recommendation:
    base:
      url: http://localhost:8080/dir/

---

spring:
  config:
    activate:
      on-profile: prod

